spring:
  datasource:
    url: jdbc:mysql://localhost:3306/es-test?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: 123456
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300

mybatis:
  mapper-locations: classpath:mapper/*Dao.xml

